import Head from "next/head";
import { NavBar } from "../components/NavBar";
import { Main } from "../components/Main";
import About from "./sobre";

export default function Home() {
  return (
    <>
      <Head>
        <title>Eduardo Gonçalves</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Main />
    </>
  );
}
