import Head from 'next/head'
import { DM_Sans } from '@next/font/google'
import { NavBar } from '../components/NavBar'
import { Main } from '../components/Main'


const dm_sans = DM_Sans({
  weight: ['400', '700'],
  subsets: ['latin'],
})

export default function Home() {

  return (
    <div className={dm_sans.className}>
      <Head>
        <title>Eduardo Gonçalves</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Main />
    </div>
  )
}
