import Head from "next/head";
import { NavBar } from "../components/NavBar";
import { Main } from "../components/Main";
import { useState } from "react";
import styled, { createGlobalStyle, ThemeProvider } from "styled-components";
import { darkTheme, lightTheme } from "../theme";
import { ButtonEvent } from "../styles/GlobalStyled";



const StyledApp = styled.div`
  color: ${(props) => props.theme.fontColor};
`;

const GlobalStyled = createGlobalStyle`
    html,
    body {
    padding: 0;
    margin: 0;
    }

    a {
    color: inherit;
    text-decoration: none;
    }

    * {
    box-sizing: border-box;
    }

    @media (prefers-color-scheme: dark) {
    html {
        color-scheme: dark;
    }
    body {
		background-color: ${(props) => props.theme.body};
	}
    }

`;



export default function Home() {

  const [theme, setTheme] = useState("light");

  const themeToggler = () => {
    theme === "light" ? setTheme("dark") : setTheme("light");
  };

  return (
    <>
      <ThemeProvider theme={theme === "light" ? lightTheme : darkTheme}>
        <GlobalStyled />
     <StyledApp>
     <Head>
        <title>Eduardo Gonçalves</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <ButtonEvent onClick={() => themeToggler()}>☼
      </ButtonEvent>
      <Main />
     </StyledApp>
      </ThemeProvider>
    </>
  );
}
